import { Heebo } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";

const heebo = Heebo({
  subsets: ["latin"],
  variable: "--font-heebo",
  // Optional: Add weights/styles you need
  weight: ["300","400", "500", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${heebo.variable} font-sans antialiased`}>
      <Header />
        {children}
      </body>
    </html>
  );
}